name: BedWars 1v1
api: 3.x.x
version: 1.0.0
main: vixikhd\BedWars\BedWars
author: ShadowBonnie, dantedevs
description: a bedwars 1v1 plugin 

permissions:
  bw.cmd:
    description: Permission to all Bedwars commands
    default: op
    children:
      bw.cmd.help:
        description: Permission for /bw help
        default: op
      bw.cmd.create:
        description: Permission for /bw create
        default: op
      bw.cmd.remove:
        description: Permission for /bw remove
        default: op
      bw.cmd.set:
        description: Permission for /bw set
        default: op
      bw.cmd.arenas:
        description: Permission for /bw arenas
        default: op
      bw.cmd.test:
        description: Permission for /bw test
        default: op
      bw.cmd.stoptest:
        description: Permission for /bw stoptest
        defaut: op